# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    
jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
    - name: npm install build and test  
      run: |
          npm i
          npm run build --if-present
          npm test
      env : 
        CI : true  
  create-file:
      runs-on: ubuntu-latest
      steps:
      - name: Create file
        run: |
          printf "Hello\nWorld\n" > hw.txt
  fetch:
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v2
        - name: Fetch data
          run: |
              curl https://fake-movie-database-api.herokuapp.com/api?s=batman -o myfile.json   
  deploy:
    runs-on: ubuntu-latest
    needs : build
    steps:
      - uses: actions/checkout@v2
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "test-react-app-cicd"
          heroku_email: "sunitagamne16@gmail.com"
          appdir: ""
          healthcheck: "https://covid-19-test-cicd-actions-1.herokuapp.com/"
          env_file: ".env"  
  
