# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "covid-19-test-cicd-actions-1"
          heroku_email: "sunitagamne16@gmail.com"
          appdir: ""
          healthcheck: "https://covid-19-test-cicd-actions-1.herokuapp.com/"
          env_file: ".env"  
  curl:
    runs-on: ubuntu-latest
    steps:
    - name: curl
      uses: wei/curl@master
      with:
        args: http://localhost:7860/api/v1.0/vendor/vendorDetails
