# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
    - name: npm install build and test  
      run: |
          npm i
          npm run build --if-present
          npm test
      env : 
        CI : true  
  fetch :
     runs-on: ubuntu-latest
     steps:
      - uses: actions/checkout@v2
      - name: fetch data using curl
        run: |
            HTTP_CODE=$(curl --write-out "%{http_code}\n" "https://doorstep-node-api.herokuapp.com/api/v1.0/vendor/vendorDetails" --output output.txt )
            echo $HTTP_CODE
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "gauribane16-hd-test-1"
          heroku_email: "sunitagauri16@gmail.com"
