# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    
defaults:
  run:
    working-directory: src
    
jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
    - name: npm install build and test  
      run: |
          npm i
          npm run build --if-present
          npm test
      env : 
        CI : true  
  fetch :
     runs-on: ubuntu-latest
     steps:
      - uses: actions/checkout@v2
      - name: Create folder
        run: |
          sudo mkdir -p /Test 
      - uses: actions/checkout@v2
      - name: fetch data using curl
        run: |
            HTTP_CODE=$(curl --write-out "%{http_code}\n" "https://samples.openweathermap.org/data/2.5/weather?q=London,uk&appid=b6907d289e10d714a6e88b30761fae22" --output output.txt )
            echo $HTTP_CODE
  deploy:
    runs-on: ubuntu-latest
    needs : build
    steps:
      - uses: actions/checkout@v2
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "covid-19-test-cicd-actions-1"
          heroku_email: "sunitagamne16@gmail.com"
          appdir: ""
          healthcheck: "https://covid-19-test-cicd-actions-1.herokuapp.com/"
          env_file: ".env"  
  
