name: Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  deploy-test-1:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: gauribane16/test-react-app-github-actions-cicd@main
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "gauribane16-hd-test-1"
          heroku_email: "sunitagauri16@gmail.com"
